<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<TITLE>第一个Zend framework程序</TITLE>
</HEAD>
<BODY>
    <?php  echo "myquestionid:".$this->questionid;
    echo "listid:".$this->listid;
    echo "priority:".$this->priority."<br/>";
     echo $this->label;
     echo "userid:".$this->userid;
?>
    
    <form action="<?php echo $this->baseUrl();?>/Myquestion/addquestion?questionid=<?php echo $this->questionid;?>" method="post">
        List<select name=list>
    <?php
    if(count($this->listresult)){
        for($i=0;$i<count($this->listresult);$i++)
        {
            echo "<option value=".$this->listresult[$i]['listid'].">".$this->listresult[$i]['listname']."</option>";        
        }
    }
     ?>
            
        </select>
        <a href="">create new list</a>
       <select name="priority">
            <option value="1">low</option>
            <option value="2">normal</option>
            <option value="3">high</option>
       </select>
        <input type="submit" value="submit"/>
    </form>
    
    <div>
        <form action="<?php echo $this->baseUrl()?>/List/addlist" method="post">
         new list name<br/><input type="text" name="list"/><br/>
        list decription<br/><textarea name="listdescription"/></textarea><br/>
        <input type="submit" value="submit"/>   
        </form>
    </div>
</BODY>
</HTML>